"""
********************************************************************************************
* Title: build_assets.py           |********************************************************
* Developed by: Ryan Hatch         |********************************************************
* Date: Feb 2nd 2026               |********************************************************
* Last Updated: Feb 23rd 2026      |********************************************************
* Version: 3.3                     |********************************************************
********************************************************************************************
*****************************#*| build_assets.py |******************************************
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
********************************#* Description: |*******************************************
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
* This script prepares asset files for deployment on the Solana blockchain using the Candy *
* Machine v2 standard. It processes image files from a specified source directory,         *
* generates relevant metadata JSON files, and organizes them into an output directory.     *
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
********************************************************************************************
"""
# import necessary libraries
import json
import re
import shutil
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# ---------------- SOLSPRITES CONFIG -----------------------
SRC_IMAGES_DIR = Path("../images")  # Path to source images (can have subfolders for organization, but only top-level folders are used for trait parsing)
OUT_ASSETS_DIR = Path("candy_machine/assets") # Output directory for Candy Machine assets (will be created if it doesn't exist)

# --------------- COLLECTION METADATA CONFIG ---------------
COLLECTION_NAME = "SolSprites"
SYMBOL = "SPRITE"
DESCRIPTION = "333 Elemental entities shaped at the edge of energy and form. Each sprite was designed as a focused fragment of force, blending elements, aura, color, and motion into a small but intentional presence. Together they breathe life into a living digital ecosystem built around evolving web3 utility."
EXTERNAL_URL = "https://zencrypt.tech"
SELLER_FEE_BPS = 1000

# Using my new developer wallet for the collection share since it has better security and I can rotate keys if needed without affecting the collection metadata. 
# NOTE: Make sure to replace with your own wallet address and not a placeholder when configuring.
CREATORS = [
    {"address": "FXDWzy6fdmADnHPME1wiifyX3H4gGnMAt8ncGTbiaoVw", "share": 100},
]

# Recommended:
#* - "renumber" => source indices can be any integers, but output will be sequential starting at 0 (e.g. source 5.png => output 0.png, source 31.png => output 1.png, etc.)
#* - "preserve" => source indices must start at 0 and be contiguous with no gaps, and these indices will be preserved in the output (e.g. source 0.png => output 0.png, source 1.png => output 1.png, source 2.png => output 2.png, etc.)
INDEX_MODE = "preserve"  # "renumber" or "preserve". See notes above for details.
NAME_NUMBER_WIDTH = 1    # Number of digits to pad the numeric part of the name (e.g. 3 => #001, #002, etc.). Set to 0 for no padding (e.g. #1, #2, etc.).

# Optional features:
CLEAN_OUTPUT_NUMERIC_ASSETS = True 
# If True, will delete existing numeric .png and .json files in the output dir before writing new ones. Set to False to keep existing files (useful if you want to preserve manually added metadata or images that aren't generated by this script).
WRITE_INDEX_MAP = True 
# If True, will write an index_map.json file that maps source indices to output indices and includes the original source file paths. Useful for tracking and debugging, especially if renumbering or if source indices are non-contiguous.
WRITE_TRAIT_AUDIT = True 
# If True, will write a _trait_audit.json file that summarizes the traits found across all items, including counts and unique values. Useful for auditing and refining trait parsing logic.
INCLUDE_VARIANTS_IN_METADATA = False 
# If True, will include Variant traits in the metadata JSON files. If False, Variant traits will be excluded from metadata but still counted in the trait audit and included in the index map for reference.

# Background fallback if no bg/mg token is found (set to "None" to disable)
DEFAULT_BACKGROUND: Optional[str] = "Black"

# COLLECTION_PNG_SRC: Optional[Path] = Path("../source_files/images/collection.png")
COLLECTION_PNG_SRC: Optional[Path] = Path("https://harlequin-magnificent-leech-671.mypinata.cloud/ipfs/bafybeicnckuujbbr3vmc74mqzmppoxld5grywvg6avq7nssc57by4cn2xq")

# If your source images have indices that you want to exclude from the output (e.g. test images, bad renders, etc.), you can specify them here. This is applied before any renumbering logic.
EXCLUDE_SOURCE_INDICES = set()  # e.g. {31, 72, 105, 200}
EXCLUDE_NAME_CONTAINS = []      # e.g. ["bad", "test"]

# ---------------- TRAIT VOCAB ----------------
# Elemental categories (e.g. fire, water, earth, air, void, electric, light, shadow)
ELEMENTS = {
    "fire", "water", "earth", "air", "void", "electric", "light", "shadow",
    #* Additional elements that might be used in traits or folder names:
    "forest", "fern", "sunflower", "spleenwort", "calypso", "magic",
}

# Type/form categories (e.g. cannabis, mushroom, halo, etc.)
TYPE_ALIASES = {
    # base
    "sprite": "Sprite",
    "regular": "Sprite",

    # mushroom family
    "mushroom": "Mushroom",
    "shroom": "Mushroom",
    "agaric": "Mushroom",
    "teonanacatl": "Mushroom",
    "psilocybe": "Mushroom",
    "shaggy": "Mushroom",
    "mane": "Mushroom",
    "reshi": "Mushroom",
    "ink": "Mushroom",
    

    # plant family
    "cannabis": "Cannabis",
    "weed": "Cannabis",
    "ganja": "Cannabis",
    "maryjane": "Cannabis",
    "marijuana": "Cannabis",
    "hemp": "Cannabis",
    "bud": "Cannabis",
    "indica": "Cannabis",
    "sativa": "Cannabis",
    "kush": "Cannabis",
    "gorilla": "Cannabis",
    "glue": "Cannabis",
    "cookies": "Cannabis",

    # other
    "goblin": "Goblin",
    "fairy": "Fairy",
    "root": "Root",
    "cubes": "Cubes",
    "cube": "Cubes",

    # plant-like sprites
    "sprout": "Plant",
    "plant": "Plant",
    "tree": "Plant",
    "fern": "Plant",
    "cactus": "Plant",
    "orchid": "Plant",
    "vine": "Plant",
    "poppy": "Plant",
    "willow": "Plant",
    "cedar": "Plant",
    "cypress": "Plant",
    "sunflower": "Plant",
    "spleenwort": "Plant",
    "khat": "Plant",
    "kratom": "Plant",
    "ayahuasca": "Plant",
    "cocoa": "Plant",
}

# Accessories and adornments
ACCESSORY_ALIASES = {
    "eyeglasses": "Eyeglasses",
    "glasses": "Eyeglasses",
    "sunglasses": "Sunglasses",
    "Sunglasses": "Sunglasses",
    "hat": "Hat",
    "crown": "Crown",
    "halo": "Halo",
}

# Motifs/patterns
MOTIF_ALIASES = {
    "tribal": "Tribal",
    "swirl": "Swirl",
    "double-tribal": "Double Tribal",
}

# Phrase traits (multi-token patterns)
PHRASE_TRAITS = [
    (("girl", "scout", "cookies"), ("Strain", "Girl Scout Cookies")),
    (("girl", "scout"), ("Strain", "Girl Scout")),
    (("death", "star"), ("Strain", "Death Star")),
    (("gorilla", "glue"), ("Strain", "Gorilla Glue")),
    (("pink", "kush"), ("Strain", "Pink Kush")),
    (("green", "md"), ("Strain", "Green Md")),
    (("white", "md"), ("Strain", "White Md")),
    (("death", "star"), ("Strain", "Death Star")),

    (("z", "strain"), ("Strain", "Z Strain")),
    (("golden", "teacher"), ("Strain", "Golden Teacher")),
    (("flying", "saucer"), ("Strain", "Flying Saucer")),
    (("liberty", "cap"), ("Strain", "Liberty Cap")),
    (("azure", "cap"), ("Strain", "Azure Cap")),
    # ((shaggy := "shaggy", mane := "mane"), ("Strain", "Shaggy Mane")),  # Example of using walrus operator for readability
    (("shaggy", "mane"), ("Strain", "Shaggy Mane")),
    (("inky", "cap"), ("Strain", "Inky Cap")),
    (("khat", "plant"), ("Strain", "Khat Plant")),
    (("cocoa", "plant"), ("Strain", "Cocoa Plant")),
    (("ayahuasca", "plant"), ("Strain", "Ayahuasca Plant")),
    (("poppy", "plant"), ("Strain", "Poppy Plant")),
    (("opium", "poppy"), ("Strain", "Opium Poppy")),
    (("willow", "herb"), ("Strain", "Willow Herb")),
    (("willow", "tree"), ("Strain", "Willow Tree")),
    (("philosophers", "stone"), ("Strain", "Philosophers Stone")),
    (("wavy", "caps"), ("Strain", "Wavy Caps")),
    (("psilocyben", "cubensis"), ("Strain", "Psilocyben Cubensis")),
    (("sacred", "mexica"), ("Strain", "Sacred Mexica")),
    (("san", "pedro"), ("Strain", "San Pedro")),
    # (("shaggy", "mane"), ("Strain", "Shaggy Mane")),
    (("swirl", "echo"), ("Motif", "Swirl Echo")),
    (("double", "tribal"), ("Motif", "Double Tribal")),
    (("double", "tribal", "aura"), ("Aura Style", "Double Tribal")),
    (("double", "aura"), ("Aura Style", "Double")),
    (("knobby", "tops"), ("Strain", "Knobby Tops")),
]

# Strain tokens (single-word indicators of specific strains or variants, not already covered by phrase traits)
STRAIN_TOKENS = {
    "indica",
    "sativa",
    "kush",
    "bohemica",
    "borneo",
    "cyanscens",
    "cubensis",
    "psilocyben",
    "psilocybin",
    "teonanacatl",
    "reshi",
    "agaric",
    # "shaggy",
    # "mane",
    "ink",
    "dmt",
    "kratom",
}

# Strains that should force Type= Mushroom even if no type token is present. This is based on known mushroom strains, any strain names here should be categorized as Mushroom even if the filename doesn't explicitly include a type token.
MUSHROOM_STRAINS = {
    "Golden Teacher",
    "Psilocyben Cubensis",
    "Sacred Mexica",
    "Wavy Caps",
    "Shaggy Mane",
    "Liberty Cap",
    "Azure",
    "Knobby Tops",
    "Flying Saucer",
    "Psilocybin",
    "Z Strain",
    "Philosophers Stone",
}

# Strains that should force Type= Cannabis even if no type token is present. This is based on known cannabis strains, any strain names here should be categorized as cannabis even if the filename doesn't explicitly include a type token.
CANNABIS_STRAINS = {
    "Death Star",
    "Gorilla Glue",
    "Girl Scout Cookies",
    "Green Md",
    "White Md",
    "Pink Kush",
    "Kush",
    "Indica",
    "Sativa",
}

# Strains that should force Type= Plant even if no type token is present. This is based on known plant strains, any strain names here should be categorized as Plant even if the filename doesn't explicitly include a type token.
PLANT_STRAINS = {
    "Khat Plant",
    "Cocoa Plant",
    "Poppy Plant",
    "Willow Tree",
    "San Pedro",
    "Dmt",
    "Kratom",
    "Borneo",
    "Ayahuasca Plant",
}

# Color tokens and their normalized forms. This is used to identify color traits and normalize them to a consistent format. You can expand this list with any additional color tokens you expect to encounter in your filenames.
COLOR_ALIASES = {
    "grey": "Gray",
    "gray": "Gray",
    "charcoal": "Charcoal",
    "cream": "Cream",
    "coal": "Coal",
    "ivory": "Ivory",
    "tan": "Tan",
    "azure": "Azure",
    "cyan": "Cyan",
    "teal": "Teal",
    "magenta": "Magenta",
    "purple": "Purple",
    "violet": "Violet",
    "pink": "Pink",
    "orange": "Orange",
    "yellow": "Yellow",
    "red": "Red",
    "green": "Green",
    "blue": "Blue",
    "black": "Black",
    "white": "White",
    "gold": "Gold",
    "silver": "Silver",
    "ember": "Ember",
    "lava": "Lava",
    "redbackdrop": "Red Backdrop",
    "bar": "Bar",
    "dive-bar": "Dive Bar",
    "satanic-dive-bar": "Satanic Dive Bar",
    "solana-convention": "Solana Convention",
    "nft-nyc": "Nft Nyc",
    "parchment": "Parchment",
    "brown": "Brown",
    "beige": "Beige",
}

# Additional color tokens that are recognized as colors but don't have specific normalized forms (they will be title-cased). This is used to catch any color tokens that aren't in the COLOR_ALIASES but should still be treated as colors.
EXTRA_COLOR_TOKENS = {
    "delicate", "seashell", "ivory", "peach", "mint", "sage", "olive", "mustard", "cobalt", "indigo", "plum", "rose", "blush", "coral", "apricot", "bronze", "copper", "steel", "slate", "ash", "charcoal", "cream", "coal", "tan", "azure", "cyan", "teal", "magenta", "purple", "violet", "pink", "orange", "yellow", "red", "green", "blue", "black", "white", "gold", "silver",
}

# Regular expressions for parsing indices from filenames and identifying numeric asset files. The IDX_RE looks for a numeric prefix followed by an underscore (e.g. "000_", "31_", etc.) to extract the source index. The NUMERIC_ASSET_RE is used to identify files that are named with just a number and .png or .json extension, which are the expected output asset files.
IDX_RE = re.compile(r"^(\d{1,4})_")
NUMERIC_ASSET_RE = re.compile(r"^\d+\.(png|json)$", re.IGNORECASE)

# Tokens that would otherwise be treated as variants but we want to ignore (e.g., common words that aren't meaningful traits).
VARIANT_IGNORE = {"variant", "variant2"}

# Utility functions for parsing and normalizing traits from filenames. These functions help convert raw tokens from the filenames into structured traits that can be included in the metadata JSON files.
def titleish(s: str) -> str:
    s = s.replace("-", " ").replace(".", " ").strip()
    return " ".join(w.capitalize() for w in s.split() if w)


def normalize_color(token: str) -> str:
    t = token.lower().strip()
    return COLOR_ALIASES.get(t, titleish(t))


def is_color_token(token: str) -> bool:
    t = token.lower().strip()
    return t in COLOR_ALIASES or t in EXTRA_COLOR_TOKENS


def validate_config() -> None:
    if not OUT_ASSETS_DIR.parts:
        raise SystemExit("OUT_ASSETS_DIR is invalid.")

    total_share = sum(int(c.get("share", 0)) for c in CREATORS)
    if total_share != 100:
        raise SystemExit(f"CREATORS shares must sum to 100. Got {total_share}.")

    for c in CREATORS:
        addr = c.get("address", "")
        if not addr or "YOUR_" in addr or "WALLET" in addr:
            raise SystemExit("Set CREATOR address in CREATORS (replace placeholder).")

    if INDEX_MODE not in {"renumber", "preserve"}:
        raise SystemExit('INDEX_MODE must be "renumber" or "preserve".')


def clean_output_dir() -> None:
    if not OUT_ASSETS_DIR.exists():
        return

    for p in OUT_ASSETS_DIR.iterdir():
        if p.is_file() and (NUMERIC_ASSET_RE.match(p.name) or p.name in {
            "collection.json", "collection.png", "index_map.json", "_trait_audit.json"
        }):
            p.unlink(missing_ok=True)


def add_bucket(bucket: Dict[str, List[str]], trait_type: str, value: str) -> None:
    if not value:
        return
    bucket.setdefault(trait_type, [])
    if value not in bucket[trait_type]:
        bucket[trait_type].append(value)

# This function converts the bucket dictionary, which maps trait types to lists of values, into a list of attribute dictionaries in the format expected by the Candy Machine metadata. It also applies a specific ordering to the traits, with any remaining traits added at the end in sorted order.
def bucket_to_attributes(bucket: Dict[str, List[str]]) -> List[Dict[str, str]]:
    order = [
        "Element",
        "Type",
        "Strain",
        "Background",
        "Sprite Color",
        "Aura",
        "Aura Style",
        "Motif",
        "Accessory",
        "Variant",
    ]
    attrs: List[Dict[str, str]] = []
    for t in order:
        for v in bucket.get(t, []):
            attrs.append({"trait_type": t, "value": v})

    remaining = sorted(set(bucket.keys()) - set(order))
    for t in remaining:
        for v in bucket.get(t, []):
            attrs.append({"trait_type": t, "value": v})

    return attrs


def tokenize(stem: str) -> List[str]:
    raw = [t for t in stem.lower().split("_") if t]
    if raw and raw[0].isdigit():
        raw = raw[1:]

    out: List[str] = []
    for t in raw:
        if t.startswith("bg-") or t == "bg" or (t.startswith("bg") and len(t) > 2):
            out.append(t)
        elif t.startswith("mg-") or t == "mg" or (t.startswith("mg") and len(t) > 2):
            out.append(t)
        else:
            out.append(t)
    return out


def apply_phrase_traits(tokens: List[str], used: set, bucket: Dict[str, List[str]]) -> None:
    for phrase, (tt, val) in sorted(PHRASE_TRAITS, key=lambda x: len(x[0]), reverse=True):
        plen = len(phrase)
        for i in range(0, len(tokens) - plen + 1):
            if any((i + k) in used for k in range(plen)):
                continue
            if tuple(tokens[i:i + plen]) == phrase:
                add_bucket(bucket, tt, val)
                for k in range(plen):
                    used.add(i + k)


def parse_traits(stem: str, rel_path: Path) -> Tuple[List[Dict[str, str]], List[str]]:
    tokens = tokenize(stem)
    used = set()
    bucket: Dict[str, List[str]] = {}

    apply_phrase_traits(tokens, used, bucket)

    # Background
    background: Optional[str] = None
    for i, t in enumerate(tokens):
        if i in used:
            continue
        if t.startswith("bg-") and len(t) > 3:
            background = t[3:]
            used.add(i)
            break
        if t.startswith("mg-") and len(t) > 3:
            background = t[3:]
            used.add(i)
            break
        if t == "bg" and i + 1 < len(tokens) and (i + 1) not in used:
            background = tokens[i + 1]
            used.add(i)
            used.add(i + 1)
            break
        if t == "mg" and i + 1 < len(tokens) and (i + 1) not in used:
            background = tokens[i + 1]
            used.add(i)
            used.add(i + 1)
            break
        if t.startswith("bg") and t != "bg" and not t.startswith("bg-") and len(t) > 2:
            background = t[2:]
            used.add(i)
            break
        if t.startswith("mg") and t != "mg" and not t.startswith("mg-") and len(t) > 2:
            background = t[2:]
            used.add(i)
            break

    if background:
        add_bucket(bucket, "Background", normalize_color(background) if is_color_token(background) else titleish(background))
    elif DEFAULT_BACKGROUND:
        add_bucket(bucket, "Background", titleish(DEFAULT_BACKGROUND))

    # Element (token or folder fallback)
    element: Optional[str] = None
    for i, t in enumerate(tokens):
        if i not in used and t in ELEMENTS:
            element = t
            used.add(i)
            break

    if not element:
        for part in rel_path.parts:
            p = part.lower()
            if p in ELEMENTS:
                element = p
                break

    add_bucket(bucket, "Element", titleish(element or "Unknown"))

    # Type
    type_val: Optional[str] = bucket.get("Type", [None])[0]
    if type_val is None:
        for i, t in enumerate(tokens):
            if i in used:
                continue
            if t in TYPE_ALIASES:
                type_val = TYPE_ALIASES[t]
                used.add(i)
                break
    add_bucket(bucket, "Type", type_val or "Sprite")

    # Strain/specific variants (skip indices already consumed by phrase matching)
    for i, t in enumerate(tokens):
        if i in used:
            continue
        if t in STRAIN_TOKENS:
            add_bucket(bucket, "Strain", titleish(t))
            used.add(i)

    # Strains that imply a specific Type even if no type token is present
    if bucket.get("Type") == ["Sprite"]:
        if any(s in MUSHROOM_STRAINS for s in bucket.get("Strain", [])):
            bucket["Type"] = ["Mushroom"]
        elif any(s in CANNABIS_STRAINS for s in bucket.get("Strain", [])):
            bucket["Type"] = ["Cannabis"]
        elif any(s in PLANT_STRAINS for s in bucket.get("Strain", [])):
            bucket["Type"] = ["Plant"]

    # Aura
    aura_present = False
    for i, t in enumerate(tokens):
        if i in used:
            continue
        if t == "aura":
            aura_present = True
            used.add(i)
            break
    if aura_present:
        add_bucket(bucket, "Aura", "Yes")

    # Motifs
    for i, t in enumerate(tokens):
        if i in used:
            continue
        if t in MOTIF_ALIASES:
            add_bucket(bucket, "Motif", MOTIF_ALIASES[t])
            used.add(i)

    # Accessories
    for i, t in enumerate(tokens):
        if i in used:
            continue
        if t in ACCESSORY_ALIASES:
            add_bucket(bucket, "Accessory", ACCESSORY_ALIASES[t])
            used.add(i)

    # Sprite colors (remaining color tokens)
    sprite_colors: List[str] = []
    for i, t in enumerate(tokens):
        if i in used:
            continue
        if is_color_token(t) and t.lower() not in ELEMENTS:
            sprite_colors.append(normalize_color(t))
            used.add(i)
    if sprite_colors:
        add_bucket(bucket, "Sprite Color", " / ".join(sprite_colors))

    # Track leftover tokens as Variant traits
    leftovers: List[str] = []
    unknown_tokens: List[str] = []
    for i, t in enumerate(tokens):
        if i in used:
            continue
        if t in {"bg", "mg"}:
            continue
        if t in VARIANT_IGNORE:
            unknown_tokens.append(t)
            continue
        leftovers.append(t)

    # Deduplicate variants while preserving order
    seen_variant = set()
    for t in leftovers:
        tv = titleish(t)
        if tv in seen_variant:
            continue
        seen_variant.add(tv)
        add_bucket(bucket, "Variant", tv)

    return bucket_to_attributes(bucket), unknown_tokens


def make_item_json(idx: int, source_path: Path, rel_path: Path) -> Dict:
    num = f"{idx:0{NAME_NUMBER_WIDTH}d}" if NAME_NUMBER_WIDTH > 0 else str(idx)
    attrs, _unknown = parse_traits(source_path.stem, rel_path)

    base: Dict = {
        "name": f"{COLLECTION_NAME} #{num}",
        "symbol": SYMBOL,
        "description": DESCRIPTION,
        "seller_fee_basis_points": SELLER_FEE_BPS,
        "image": f"{idx}.png",
        "attributes": attrs,
        "properties": {
            "files": [{"uri": f"{idx}.png", "type": "image/png"}],
            "category": "image",
            "creators": CREATORS,
        },
    }
    if EXTERNAL_URL:
        base["external_url"] = EXTERNAL_URL
    return base


def make_collection_json() -> Dict:
    base: Dict = {
        "name": COLLECTION_NAME,
        "symbol": SYMBOL,
        "description": DESCRIPTION,
        "seller_fee_basis_points": SELLER_FEE_BPS,
        "image": "collection.png",
        "properties": {
            "files": [{"uri": "collection.png", "type": "image/png"}],
            "category": "image",
            "creators": CREATORS,
        },
    }
    if EXTERNAL_URL:
        base["external_url"] = EXTERNAL_URL
    return base


def discover_images() -> List[Tuple[int, Path]]:
    pngs: List[Tuple[int, Path]] = []
    for p in SRC_IMAGES_DIR.rglob("*.png"):
        if p.name.lower() == "collection.png":
            continue

        m = IDX_RE.match(p.name)
        if not m:
            continue

        src_idx = int(m.group(1))
        if src_idx in EXCLUDE_SOURCE_INDICES:
            continue

        name_lower = p.name.lower()
        if any(s.lower() in name_lower for s in EXCLUDE_NAME_CONTAINS):
            continue

        pngs.append((src_idx, p))

    pngs.sort(key=lambda t: (t[0], str(t[1]).lower()))
    return pngs


def ensure_preserve_indices_contiguous(src_indices: List[int]) -> None:
    if not src_indices:
        raise SystemExit("No images found.")
    if src_indices[0] != 0:
        raise SystemExit(f'INDEX_MODE="preserve" requires starting at 0. Found start {src_indices[0]}.')
    expected = list(range(0, len(src_indices)))
    if src_indices != expected:
        missing = sorted(set(expected) - set(src_indices))
        extra = sorted(set(src_indices) - set(expected))
        raise SystemExit(f'INDEX_MODE="preserve" requires no gaps. Missing: {missing[:20]} Extra: {extra[:20]}')


def main() -> None:
    validate_config()

    if not SRC_IMAGES_DIR.exists():
        raise SystemExit(f"Missing source dir: {SRC_IMAGES_DIR}")

    OUT_ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    if CLEAN_OUTPUT_NUMERIC_ASSETS:
        clean_output_dir()

    pngs = discover_images()
    if not pngs:
        raise SystemExit(f"No matching PNGs like '000_*.png' found under: {SRC_IMAGES_DIR}")

    seen_idx: Dict[int, Path] = {}
    duplicates = []
    for src_idx, p in pngs:
        if src_idx in seen_idx:
            duplicates.append((src_idx, seen_idx[src_idx], p))
        else:
            seen_idx[src_idx] = p
    if duplicates:
        lines = "\n".join(f"{i}: {a} | {b}" for i, a, b in duplicates[:20])
        raise SystemExit(f"Duplicate source indices detected:\n{lines}")

    src_indices = [i for i, _ in pngs]
    if INDEX_MODE == "preserve":
        ensure_preserve_indices_contiguous(src_indices)

    index_map = []
    unknown_counter = Counter()
    trait_counts = Counter()
    values_by_trait = defaultdict(set)
    variants_by_index = {}

    for out_idx, (src_idx, src_path) in enumerate(pngs):
        final_idx = src_idx if INDEX_MODE == "preserve" else out_idx

        out_png = OUT_ASSETS_DIR / f"{final_idx}.png"
        out_json = OUT_ASSETS_DIR / f"{final_idx}.json"

        shutil.copy2(src_path, out_png)

        # rel_path = src_path.relative_to(SRC_IMAGES_DIR)
        # attrs, unknown_tokens = parse_traits(src_path.stem, rel_path)

        # meta = make_item_json(final_idx, src_path, rel_path)
        # meta["attributes"] = attrs
        # out_json.write_text(json.dumps(meta, indent=2), encoding="utf-8")

        # for a in attrs:
        #     tt = a.get("trait_type", "")
        #     vv = a.get("value", "")
        #     trait_counts[tt] += 1
        #     if vv:
        #         values_by_trait[tt].add(vv)

        rel_path = src_path.relative_to(SRC_IMAGES_DIR)

        attrs_all, unknown_tokens = parse_traits(src_path.stem, rel_path)

        # Keep per-item variants for the audit log only
        variant_vals = [
            a.get("value", "")
            for a in attrs_all
            if a.get("trait_type") == "Variant" and a.get("value")
        ]
        if variant_vals:
            variants_by_index[str(final_idx)] = variant_vals

        # Strip Variant from the metadata JSONs (0..N-1.json)
        attrs_meta = attrs_all if INCLUDE_VARIANTS_IN_METADATA else [
            a for a in attrs_all if a.get("trait_type") != "Variant"
        ]

        meta = make_item_json(final_idx, src_path, rel_path)
        meta["attributes"] = attrs_meta
        out_json.write_text(json.dumps(meta, indent=2), encoding="utf-8")

        # Audit counts should still include Variant
        for a in attrs_all:
            tt = a.get("trait_type", "")
            vv = a.get("value", "")
            trait_counts[tt] += 1
            if vv:
                values_by_trait[tt].add(vv)

        for t in unknown_tokens:
            unknown_counter[t] += 1

        index_map.append(
            {"final_idx": final_idx, "src_idx": src_idx, "variants_by_index": variants_by_index, "src_file": str(rel_path).replace("\\", "/")}
        )

    (OUT_ASSETS_DIR / "collection.json").write_text(
        json.dumps(make_collection_json(), indent=2),
        encoding="utf-8",
    )

    collection_src = COLLECTION_PNG_SRC
    if collection_src is None:
        candidate = SRC_IMAGES_DIR / "collection.png"
        if candidate.exists():
            collection_src = candidate

    if collection_src and collection_src.exists():
        shutil.copy2(collection_src, OUT_ASSETS_DIR / "collection.png")

    if WRITE_INDEX_MAP:
        (OUT_ASSETS_DIR / "index_map.json").write_text(
            json.dumps(index_map, indent=2),
            encoding="utf-8",
        )

    if WRITE_TRAIT_AUDIT:
        audit = {
            "items_written": len(pngs),
            "index_mode": INDEX_MODE,
            "trait_types_seen": dict(trait_counts),
            "unique_values_by_trait": {k: sorted(list(v)) for k, v in values_by_trait.items()},
            "unknown_token_counts": dict(unknown_counter.most_common(200)),
            "notes": [
                "If important tokens show up under unknown_token_counts, add them to TYPE_ALIASES / ACCESSORY_ALIASES / MOTIF_ALIASES / COLOR_ALIASES.",
                "Background is parsed from bg-* patterns only (bg-cream, bg-white, bg-red, etc.).",
            ],
        }
        (OUT_ASSETS_DIR / "_trait_audit.json").write_text(
            json.dumps(audit, indent=2),
            encoding="utf-8",
        )

    print(f"Done. Wrote {len(pngs)} items to {OUT_ASSETS_DIR}")


if __name__ == "__main__":
    main()
